language: node_js
node_js:
  - 12
branches:
  only:
    - master
    - develop
jobs:
  include:
    - stage: api-develop-deploy
      script: skip
      before_deploy:
        - cd buhocenter-backend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: api-develop-buhocenter
        skip_cleanup: true
        on:
          repo: mapf98/fase3-dsw
          branch: master
    - stage: develop-deploy
      script: skip
      before_deploy:
        - cd buhocenter-frontend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: develop-buhocenter
        skip_cleanup: true
        on:
          repo: mapf98/fase3-dsw
          branch: master
    - stage: api-blue-deploy
      script: skip
      before_deploy:
        - cd buhocenter-backend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: api-blue-buhocenter
        skip_cleanup: true
        on:
          repo: mapf98/fase3-dsw
          branch: master
    - stage: blue-deploy
      script: skip
      before_deploy:
        - cd buhocenter-frontend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: blue-buhocenter
        skip_cleanup: true
        on:
          repo: mapf98/fase3-dsw
          branch: master
    - stage: api-green-deploy
      script: skip
      before_deploy:
        - cd buhocenter-backend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_2
        app: api-green-buhocenter
        skip_cleanup: true
        on:
          repo: mapf98/fase3-dsw
          branch: master
    - stage: green-deploy
      script: skip
      before_deploy:
        - cd buhocenter-frontend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_2
        app: green-buhocenter
        skip_cleanup: true
        on:
          repo: mapf98/fase3-dsw
          branch: master
      