language: node_js
node_js:
  - 12
branches:
  only:
    - master
    - develop
jobs:
  include:
    - stage: api-develop
      if: branch = master AND $DEPLOY_VAR = blue
      before_install:
        - cd buhocenter-backend
      install:
        - npm install
      script:
        - "npm test"
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: api-develop-buhocenter
        on:
          repo: mapf98/fase3-dsw          
          branch: master
    - stage: client-develop
      if: branch = master AND $DEPLOY_VAR = blue
      before_install:
        - cd buhocenter-frontend
      install:
        - npm install
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: develop-buhocenter
        on:
          repo: mapf98/fase3-dsw
          branch: master
