language: node_js
node_js:
  - 12
branches:
  only:
    - master
    - develop
jobs:
  include:
    - stage: api-develop
      if: branch = develop
      script: npm run test
      before_deploy:
        - cd buhocenter-backend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: api-develop-buhocenter
        skip_cleanup: true
        on:
          repo: ingswucab/consorcio2-buhocenter          
          branch: develop
    - stage: develop
      if: branch = develop
      script: skip
      before_deploy:
        - cd buhocenter-frontend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: develop-buhocenter
        skip_cleanup: true
        on:
          repo: ingswucab/consorcio2-buhocenter
          branch: develop
    - stage: api-blue
      if: branch = master AND $DEPLOY_VAR = blue
      script: npm run test
      before_deploy:
        - cd buhocenter-backend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: api-blue-buhocenter
        skip_cleanup: true
        on:
          repo: ingswucab/consorcio2-buhocenter
          branch: master
    - stage: blue
      if: branch = master AND $DEPLOY_VAR = blue
      script: skip
      before_deploy:
        - cd buhocenter-frontend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_1
        app: blue-buhocenter
        skip_cleanup: true
        on:
          repo: ingswucab/consorcio2-buhocenter
          branch: master
    - stage: api-green
      if: branch = master AND $DEPLOY_VAR = green
      script: npm run test
      before_deploy:
        - cd buhocenter-backend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_2
        app: api-green-buhocenter
        skip_cleanup: true
        on:
          repo: ingswucab/consorcio2-buhocenter
          branch: master
    - stage: green
      if: branch = master AND $DEPLOY_VAR = green
      script: skip
      before_deploy:
        - cd buhocenter-frontend
      deploy:
        provider: heroku
        api_key: $HK_API_KEY_2
        app: green-buhocenter
        skip_cleanup: true
        on:
          repo: ingswucab/consorcio2-buhocenter
          branch: master
      