export default {
    mutations: {
        SET_CART: 'SET_CART',
        ADD_PRODUCT_CHECKOUT: 'ADD_PRODUCT_CHECKOUT',
        REMOVE_PRODUCT_CHECKOUT: 'REMOVE_PRODUCT_CHECKOUT',
        SET_QUANTITY_PRODUCT: 'SET_QUANTITY_PRODUCT',
        REMOVE_PRODUCT_CART: 'REMOVE_PRODUCT_CART',
    },
    getters: {
        GET_CART_OBJECT: 'GET_CART_OBJECT',
        GET_PRODUCTS_CHECKOUT: 'GET_PRODUCTS_CHECKOUT',
        GET_TOTAL_PRICE_CHECKOUT: 'GET_TOTAL_PRICE_CHECKOUT',
    },
    actions: {
        ADD_PRODUCT_TO_CART: 'ADD_PRODUCT_TO_CART',
        ADD_SERVICE_TO_CART: 'ADD_SERVICE_TO_CART',
        GET_ITEMS_CARS: 'GET_ITEMS_CARS',
        DELETE_PRODUCT_CART: 'DELETE_PRODUCT_CART',
    },
};
