export enum ConfigKeys {
    API_PORT = 'API_PORT',
    CONNECTION = 'CONNECTION',
    HOST = 'HOST',
    DATABASE_PORT = 'DATABASE_PORT',
    USERNAME = 'USERNAME',
    PASSWORD = 'PASSWORD',
    DATABASE = 'DATABASE',
    SYNCHRONIZE = 'SYNCHRONIZE',
    COINGATE_API_KEY = 'COINGATE_API_KEY',
    BLOCKCHAIN_MODE = 'BLOCKCHAIN_MODE',
    PRODUCTION_URL = 'PRODUCTION_URL',
}
