export enum ConfigKeys {
    CONNECTION = 'CONNECTION',
    HOST = 'HOST',
    DATABASE_PORT = 'DATABASE_PORT',
    USERNAME = 'USERNAME',
    PASSWORD = 'PASSWORD',
    DATABASE = 'DATABASE',
    PORT = 'PORT',
    SYNCHRONIZE = 'SYNCHRONIZE',
}
